redis:
  host: "localhost"
  port: 6379
  password: ""            # no password can be empty
  db: 0                   # db no
  decode_responses: true  # auto decode response as string
  socket_timeout: 5       # timeout for socket connect
  retry_on_timeout: true  # retry for timeout
